"use client";
import {useEffect,useMemo,useState} from 'react';import {useSearchParams} from 'next/navigation';import {FileTree} from '@/components/editor/FileTree';import {FileSearch} from '@/components/editor/FileSearch';import {EditorTabs} from '@/components/editor/EditorTabs';import {CodeEditor} from '@/components/editor/CodeEditor';import {EditorToolbar} from '@/components/editor/EditorToolbar';import {EditorStatusBar} from '@/components/editor/EditorStatusBar';import {CreateFileDialog} from '@/components/editor/CreateFileDialog';import {DeleteFileDialog} from '@/components/editor/DeleteFileDialog';import {ZipDialog} from '@/components/zip/ZipDialog';
export default function Editor(){const q=useSearchParams(),owner=q.get('owner')||'',repo=q.get('repo')||'',initial=q.get('branch')||'main';const[branch,setBranch]=useState(initial),[tree,setTree]=useState<any[]>([]),[tabs,setTabs]=useState<any[]>([]),[active,setActive]=useState(''),[filter,setFilter]=useState(''),[create,setCreate]=useState(false),[del,setDel]=useState(false),[zip,setZip]=useState(false),[status,setStatus]=useState('Ready');
async function loadTree(){if(!owner||!repo)return;const r=await fetch(`/api/github/repo/tree?owner=${owner}&repo=${repo}&branch=${encodeURIComponent(branch)}`);const d=await r.json();if(d.error){setStatus(d.error);return}setTree(d.tree||[])}useEffect(()=>{loadTree()},[owner,repo,branch]);
const items=useMemo(()=>tree.filter(x=>x.type==='blob'&&(!filter||x.path.toLowerCase().includes(filter.toLowerCase()))),[tree,filter]);const current=tabs.find(x=>x.path===active);
async function open(item:any){setStatus('Loading…');const r=await fetch(`/api/github/repo/file?owner=${owner}&repo=${repo}&path=${encodeURIComponent(item.path)}&branch=${encodeURIComponent(branch)}`);const d=await r.json();if(d.error){setStatus(d.error);return}setTabs(t=>[...t.filter(x=>x.path!==item.path),{path:item.path,name:item.path.split('/').pop(),sha:d.sha,content:d.content||'',dirty:false}]);setActive(item.path);setStatus('Ready')}
function edit(content:string){setTabs(t=>t.map(x=>x.path===active?{...x,content,dirty:true}:x))}
async function save(){if(!current)return;setStatus('Committing…');const r=await fetch('/api/github/repo/update-file',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({owner,repo,path:current.path,content:current.content,sha:current.sha,branch,message:`Update ${current.path}`})});const d=await r.json();if(d.error){setStatus(d.error);return}setTabs(t=>t.map(x=>x.path===active?{...x,sha:d.content?.sha||x.sha,dirty:false}:x));setStatus('Committed successfully');loadTree()}
async function createFile(path:string){setCreate(false);if(!path)return;const r=await fetch('/api/github/repo/create-file',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({owner,repo,path,content:'',branch,message:`Create ${path}`})});const d=await r.json();if(d.error){setStatus(d.error);return}await loadTree();open({path})}
async function remove(){if(!current)return;const r=await fetch('/api/github/repo/delete-file',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({owner,repo,path:current.path,sha:current.sha,branch,message:`Delete ${current.path}`})});const d=await r.json();if(d.error){setStatus(d.error);return}setTabs(t=>t.filter(x=>x.path!==active));setActive('');setDel(false);setStatus('Deleted');loadTree()}
return <main className='editor-shell'><aside className='editor-sidebar'><b>{owner}/{repo}</b><input className='input compact' value={branch} onChange={e=>setBranch(e.target.value)}/><FileSearch onChange={setFilter}/><FileTree items={items} onOpen={open}/></aside><section className='editor-main'><div className='editor-top'><b>BlueGit Editor</b><span>{status}</span></div><EditorTabs tabs={tabs} active={active} onSelect={setActive} onClose={p=>{setTabs(t=>t.filter(x=>x.path!==p));if(active===p)setActive('')}}/><EditorToolbar onSave={save} onCreate={()=>setCreate(true)} onDelete={()=>setDel(true)} disabled={!current}/><div className='editor-wrap'>{current?<CodeEditor content={current.content} onChange={edit}/>:<div className='editor-empty'><h2>Select a file</h2><p>Open a file from the repository tree.</p></div>}</div><EditorStatusBar path={active} dirty={current?.dirty}/></section><button className='btn btn-secondary editor-floating' onClick={()=>setZip(true)}>Export ZIP</button><CreateFileDialog open={create} onClose={()=>setCreate(false)} onCreate={createFile}/><DeleteFileDialog open={del} onClose={()=>setDel(false)} onDelete={remove} path={active}/><ZipDialog open={zip} onClose={()=>setZip(false)} files={tabs.map(x=>({path:x.path,content:x.content}))}/></main>}
